FROM tomcat:8.0.20-jre8

# Copy the WAR file generated by Maven into Tomcat webapps directory
COPY target/*.war /usr/local/tomcat/webapps/hiring.war

# Expose Tomcat default port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]

